Logger_Config:
  log_level: DEBUG
  logger_type: redis
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  terminal: {}
  file:
    filename: MAPLE.log
  mqtt:
    broker: redis
    port: 1883
    topic: logs
  redis:
    host: redis
    port: 6379
    channel: Plan:logs
knowledgeIn:
  properties: null
knowledgeOut:
  properties:
    - property:
        type: data
        name: new_plan
        class: new_plan
        topic: /new_plan
        QoS: 10
    - property:
        type: data
        name: direction
        class: direction
        topic: /direction
        QoS: 10
eventIn:
  properties:
    - property:
        type: event
        name: anomaly
        class: "-"
        topic: /anomaly
        QoS: 10
    - property:
        type: event
        name: anomaly
        class: "-"
        topic: /anomaly
        QoS: 10
eventOut:
  properties:
    - property:
        type: plan
        name: new_plan
        class: "-"
        topic: /new_plan
        QoS: 10
Event_Manager_Config:
  protocol: mqtt
  host: emqx
  port: 1883
Message_Manager_Config:
  protocol: mqtt
  host: emqx
  port: 1883
Knowledge_Config:
  knowledge_type: redis
  host: redis
  port: 6379
  db: 0
