Logger_Config:
  log_level: DEBUG
  logger_type: redis
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  terminal: {}
  file:
    filename: MAPLE.log
  mqtt:
    broker: redis
    port: 1883
    topic: logs
  redis:
    host: redis
    port: 6379
    channel: Execute:logs
knowledgeIn:
  properties:
    - property:
        type: data
        name: isLegit
        class: isLegit
        topic: /isLegit
        QoS: 10
    - property:
        type: data
        name: directions
        class: directions
        topic: /directions
        QoS: 10
knowledgeOut:
  properties:
    - property:
        type: data
        name: spin_config
        class: spin_config
        topic: /spin_config
        QoS: 10
eventIn:
  properties:
    - property:
        type: event
        name: new_plan
        class: "-"
        topic: /new_plan
        QoS: 10
    - property:
        type: event
        name: isLegit
        class: "-"
        topic: /isLegit
        QoS: 10
eventOut:
  properties:
    - property:
        type: event
        name: /spin_config
        class: "-"
        topic: /spin_config
        QoS: 10
Event_Manager_Config:
  protocol: mqtt
  broker: emqx
  port: 1883
Message_Manager_Config:
  protocol: mqtt
  broker: emqx
  port: 1883
Knowledge_Config:
  knowledge_type: redis
  host: redis
  port: 6379
  db: 0
