Logger_Config:
  log_level: DEBUG
  logger_type: redis
  format: "%(asctime)s} - %(name)s - %(levelname)s - %(message)s" # same format as others; adjust if needed
  terminal: {}
  file:
    filename: MAPLE.log
  mqtt:
    broker: redis
    port: 1883
    topic: logs
  redis:
    host: redis
    port: 6379
    channel: Trustworthiness:logs

knowledgeIn:
  properties: null

knowledgeOut:
  properties: null

eventIn:
  properties:
    - property:
        type: event
        name: anomaly
        class: "-"
        topic: /anomaly
        QoS: 10
    - property:
        type: event
        name: new_plan
        class: "-"
        topic: /new_plan
        QoS: 10
    - property:
        type: event
        name: isLegit
        class: "-"
        topic: /isLegit
        QoS: 10
    - property:
        type: event
        name: /spin_config
        class: "-"
        topic: /spin_config
        QoS: 10
    - property:
        type: event
        name: maple
        class: "-"
        topic: /maple
        QoS: 10

eventOut:
  properties:
    - property:
        type: stage
        name: stage
        class: "-"
        topic: /stage
        QoS: 10

Event_Manager_Config:
  protocol: redis
  host: redis
  port: 6379

Message_Manager_Config:
  protocol: redis
  host: redis
  port: 6379

Knowledge_Config:
  knowledge_type: redis
  host: redis
  port: 6379
  db: 0