version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  main-app:
    build: .
    container_name: main-app
    depends_on:
      redis:
        condition: service_healthy
    network_mode: "host"
    environment:
      - REDIS_HOST=localhost
    restart: unless-stopped
