Logger_Config:
  log_level: DEBUG
  logger_type: redis
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  terminal: {}
  file:
    filename: MAPLE.log
  mqtt:
    broker: redis
    port: 1883
    topic: logs
  redis:
    host: redis
    port: 6379
    channel: Analysis:logs
knowledgeIn:
  properties:
    - property:
        type: data
        name: laser_scan
        class: laser_scan
        topic: /laser_scan
        QoS: 10
knowledgeOut:
  properties: null
eventIn:
  properties:
    - property:
        type: event
        name: new_data
        class: "-"
        topic: /new_data
        QoS: 10
eventOut:
  properties:
    - property:
        type: event
        name: anomaly
        class: "-"
        topic: /anomaly
        QoS: 10
Event_Manager_Config:
  protocol: redis
  host: redis
  port: 6379
Message_Manager_Config:
  protocol: redis
  host: redis
  port: 6379
Knowledge_Config:
  knowledge_type: redis
  host: redis
  port: 6379
  db: 0
