Logger_Config:
  log_level: DEBUG
  logger_type: redis
  format: "%(asctime)s} - %(name)s - %(levelname)s - %(message)s" # same format as others; adjust if needed
  terminal: {}
  file:
    filename: MAPLE.log
  mqtt:
    broker: redis
    port: 1883
    topic: logs
  redis:
    host: redis
    port: 6379
    channel: legitimate:logs

knowledgeIn:
  properties: null

knowledgeOut:
  properties: null

eventIn:
  properties:
    - property:
        type: event
        name: new_plan
        class: "-"
        topic: /new_plan
        QoS: 10


eventOut:
  properties:
    - property:
        type: event
        name: isLegit
        class: "-"
        topic: isLegit
        QoS: 10


mqtt_broker: "localhost"
mqtt_port: 1883

mqtt_subscribe_topics:
  - "/Scan"

mqtt_publish_topics:
  - "monitor/event"

Event_Manager_Config:
  protocol: redis
  host: redis
  port: 6379

Message_Manager_Config:
  protocol: redis
  host: redis
  port: 6379

Knowledge_Config:
  knowledge_type: redis
  host: redis
  port: 6379
  db: 0
